name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        # Recommended is to use version because its the working version if you ref a branch then a breaking change might happen and break your workflow
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Mert

      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
