name: Container WF
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:14.8.0-alpine3.10

    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
          pwd
